>>> MyList = __import__('1-my_list').MyList
>>> my_list = MyList()
>>> my_list.append(10)
>>> my_list
[10]
>>> my_list.append(3)
>>> my_list
[10, 3]
>>> my_list.pop()
3
>>> my_list
[10]
>>> my_list.append(7)
>>> my_list.append(2)
>>> my_list.append(1)
>>> my_list.append(5)
>>> my_list.pop()
5
>>> my_list
[10, 7, 2, 1]
>>> my_list.print_sorted()
[1, 2, 7, 10]
>>> my_list
[10, 7, 2, 1]

>>> my_list.append(8)
>>> my_list.append(9)
>>> my_list.append(3)
>>> my_list.append(4)
>>> my_list
[8, 9, 3, 4]
>>> my_list.clear()
>>> my_list
[]
>>> my_list.append(8)
>>> my_list.append(1)
>>> my_list.append(3)
>>> new_list = my_list.copy()
>>> new_list
[8, 1, 3]
>>> new_list.count(3)
1
>>> new_list.append(3)
>>> new_list
[8, 1, 3, 3]
>>> new_list.count(3)
2
>>> my_list.index(4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: 4 is not in list
>>> my_list.index(3)
2
>>> my_list.append(8)
>>> my_list.append(9)
>>> my_list.append(3)
>>> my_list.append(4)
>>> my_list
[8, 9, 3, 4]
>>> my_list.clear()
>>> my_list
[8, 1, 3]
>>> my_list.pop(1)
1
>>> my_list
[8, 3]
>>> my_list.insert(10, 0)
>>> my_list
[8, 3, 0]
>>> my_list.insert(1, 0)
>>> my_list
[8, 0, 3, 0]

>>> my_list.print_sorted(10)
Traceback (most recent call last):
      ...
TypeError: print_sorted() takes 1 positional argument but 2 were given

>>> my_list.pop(10)
Traceback (most recent call last):
      ...
IndexError: pop index out of range

>>> my_list.append(-1)
>>> my_list.append(7)
>>> my_list
[8, 0, 3, 0, -1, 7]
>>> my_list.print_sorted()
[-1, 0, 0, 3, 7, 8]
>>> my_list.clear()
>>> my_list
[]
>>> new_list
[8, 1, 3, 3]
>>> new_list.clear()
>>> new_list
[]
